# This is a basic workflow to help you get started with Actions

name: Build PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    tags:
    - 'v*'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pandoc Document Converter
        uses: maxheld83/pandoc-action@v2

      # Runs a single command using the runners shell
      - name: Create Temp Files
        run: |
          echo JXNU Asscoiation of Computer Science
          mkdir $HOME/build/1
          mkdir $HOME/build/2
          mkdir $HOME/build/3
          mkdir $HOME/build/4
          mkdir $HOME/build/5
          mv 1-数学.md $HOME/build/1/
          mv 2-数据结构.md $HOME/build/2/
          mv 3-字符串.md $HOME/build/3/
          mv 4-计算几何.md $HOME/build/4/
          mv 5-图论.md $HOME/build/5/
          


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
